name: Build and Deploy (Ubuntu Release)

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Dlang
        uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
      
      - name: Build
        run: |
          sudo apt install libsdl2-dev
          dub build -c=release --build release --compiler=$DC -a=x86_64
          mv bin/dbox bin/dbox-linux-x86_64
      
      - name: Deploy
        uses: softprops/action-gh-release@v2
        with:
          files: bin/dbox-linux-x86_64
          make_latest: true
